DROP DATABASE IF EXISTS Track;

CREATE DATABASE Track;

USE Track;

CREATE TABLE User (
id INT(8) PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL,
created DATETIME NOT NULL,
updated DATETIME NOT NULL
);

CREATE TABLE Watch (
id INT(8) PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(200) NOT NULL,
title_selector VARCHAR(200) NOT NULL,
source VARCHAR(255) UNIQUE NOT NULL,
source_name VARCHAR(100) UNIQUE NOT NULL,
price FLOAT(10) NOT NULL,
price_selector VARCHAR(200) NOT NULL,
images VARCHAR(255) NOT NULL,
image_selector VARCHAR(200) NOT NULL
);


