DROP DATABASE IF EXISTS Track;

CREATE DATABASE Track;

USE Track;

CREATE TABLE User (
id INT(8) PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL,
phone VARCHAR(15) UNIQUE NOT NULL,
status VARCHAR(10) NOT NULL,
created DATETIME NOT NULL,
updated DATETIME NOT NULL,
last_login DATETIME NOT NULL,
password_attempts INT
);

